DTC_INCLUDE += $(srctree)/../sm8550-modules/qcom/opensource/audio-kernel/include

ifeq ($(CONFIG_MACH_SONY_PDX234),y)
SOMC_TARGET_PRODUCT := pdx234
endif
ifeq ($(CONFIG_MACH_SONY_PDX237),y)
SOMC_TARGET_PRODUCT := pdx237
endif
SOMC_TARGET_OPERATOR := generic
SOMC_PLATFORM := yodo

ifeq ($(CONFIG_ARCH_KALAMA), y)

ifeq ($(SOMC_PLATFORM), yodo)
SOMC_PRODUCT_OPERATOR = $(SOMC_TARGET_PRODUCT)_$(SOMC_TARGET_OPERATOR)

ifeq ($(SOMC_PRODUCT_OPERATOR),pdx234_generic)
dtb-y += kalama-audio.dtbo

dtbo-y += kalama-audio.dtbo \
	          somc-yodo-audio-pdx234.dtbo
endif
ifeq ($(SOMC_PRODUCT_OPERATOR),pdx237_generic)
dtb-y += kalama-audio.dtbo

dtbo-y += kalama-audio.dtbo \
	          somc-yodo-audio-pdx237.dtbo
endif

else
dtbo-y += kalama-audio.dtbo \
                 kalama-audio-cdp.dtbo \
                 kalama-audio-cdp-nfc.dtbo \
                 kalama-audio-wsa883x-cdp.dtbo \
                 kalama-audio-cdp-apq.dtbo \
                 kalama-audio-mtp.dtbo \
                 kalama-audio-mtp-nfc.dtbo \
                 kalama-audio-mtp-apq.dtbo \
                 kalama-audio-qrd.dtbo \
                 kalama-audio-atp.dtbo \
                 kalama-audio-rcm.dtbo \
                 kalama-audio-rumi.dtbo \
                 kalama-audio-hdk.dtbo \
                 kalama-sg-audio-hhg.dtbo
endif
endif

ifeq ($(CONFIG_ARCH_CROW), y)
dtbo-y += crow-audio.dtbo \
                 crow-audio-idp.dtbo \
                 crow-audio-idp-wcd9395-aatc.dtbo \
                 crow-audio-idp-wcd9395-dmic.dtbo \
                 crow-audio-idp-wcd9395-wcd-dmic.dtbo \
                 crow-audio-qrd.dtbo \
                 crow-audio-atp.dtbo
endif

 always-y    := $(dtb-y) $(dtbo-y)
 subdir-y    := $(dts-dirs)
 clean-files    := *.dtb *.dtbo
